% This is the vssutsohan class that gives a format of the Ph. D report according to the Veer Surendra Sai University of Technology. 

%To use this class, write -  \documentclass{vssut_sohan}

% Good luck and save your time!

% Written by Dr. Sohan Kumar Pande

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{vssutsohan}[2020/10/10 VSSUT PhD report]

\LoadClass[a4paper,oneside,12pt]{book}

\pagestyle{plain}

%  Here the page setup based on VSSUT guideline
\setlength{\voffset}{-1in}  
\setlength{\marginparsep}{0in}  
\setlength{\marginparwidth}{0in}  
\setlength{\marginparpush}{0in}  
\setlength{\hoffset}{-1in}  
\setlength{\oddsidemargin}{3.5cm}  %
\setlength{\evensidemargin}{2.5cm} %  
\setlength{\textwidth}{15cm}
\setlength{\topmargin}{2.5cm}
\setlength{\headheight}{15pt}
\setlength{\headsep}{16pt}
\setlength{\textheight}{24cm}
\setlength{\footskip}{18pt}



















